### ISSUE TITLE
Can you turn this project into a template so I can use it as github template?

### ISSUE THREAD

**Issue by LeoQuote** [helm/charts-repo-actions-demo#19]
I can set the project name in web ui, instead of clone and push , it would be much more convenient

**Comment by davidkarlsen** [comment]
Done

**Comment by scottrigby** [comment]
Only thing to keep in mind is the README explains how users can set up their own Helm repo on GitHub using Helm GH Actions, and the demo charts aren't something you'd want to start with, but just show/prove how it works. This isn't really ideal as a template for a new Helm repo, where you'd presumably have your own charts.

So while it's a lot less awful to use as a one-click starter (GitHub template) than the clone method above, it's still not great to use as a template because you have to clear out the unnecessary bits and add in your own. I guess it's not the worst thing for this to be used as a GH template, as long as people understand these caveats.

**Comment by LeoQuote** [comment]
Thanks for you explain, it just works for me.

**Comment by invidian** [comment]
>So while it's a lot less awful to use as a one-click starter (GitHub template) than the clone method above, it's still not great to use as a template because you have to clear out the unnecessary bits and add in your own. I guess it's not the worst thing for this to be used as a GH template, as long as people understand these caveats.

I was about to report this :) I wonder, maybe it make sense to mention that in the README.md?
